language: cpp
# adapted from
# https://riptutorial.com/cmake/example/4722/configure-travis-ci-with-stock-cmake

os:
  - linux
  - osx
  - windows

env:
  - BUILD_TYPE=Release

compiler:
  - gcc

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake where CMakeLists.txt is located
  - cmake ../src -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  # once CMake has done its job we just build using make as usual
  - cmake --build . --config $BUILD_TYPE
  # if the project uses ctest we can run the tests like this
  - ctest -C $BUILD_TYPE
