name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master

    - name: Publish docker image
      uses: docker/build-push-action@v1
      with:
        name: sebranchett/testcpp
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
