name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Publish docker image
      uses: docker/build-push-action@v1
      with:
        repository: sebranchett/testcpp
        # username: ${{ secrets.DOCKER_USERNAME }}
        # password: ${{ secrets.DOCKER_PASSWORD }}
        tag_with_ref: true
        tag_with_sha: true
